language: cpp

compiler:
    - gcc

before_install:
    - git clone https://github.com/Itseez/opencv.git
    - mkdir libs
    - cd opencv && mkdir build && cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=~/libs .. && make && make install
script:
    - cmake .
    - make
    - ./highgoal.bin test
