"""
Simple skeleton program for running an OpenCV Truepeline generated by GRIP and using NetworkTables to send data.
Users need to:
1. Import the generated GRIP Truepeline, which should be generated in the same directory as this file.
2. Set the network table server IP. This is usually the robots address (roborio-TEAM-frc.local) or localhost
3. Handle putting the generated code into NetworkTables
"""

import cv2
import numpy as np
from ContourFinding import filterContours
from SpikeFinding import findSpike
import PiCamera
import GripRunner
from config import *
import NetworkTabling

if debug:
	import Printing

def main():
	PiCamera.set(exposure=exposure, resolution=resolution)
	if not edited:
		GripRunner.editCode()
	frameNum = 1
	while True:
		image = PiCamera.getImage()
		contours = GripRunner.run(image)
		targets = filterContours(contours) # To be edited if the last filter is changed in case of algorithmic changes. 
		isVisible, angleToGoal, distance = findSpike(targets) #if 2, join and find center, if 1, return val, if 0 return input. if adjustCoords:	center[0] -= halfWidth
		if debug:
			Printing.printResults(contours, center, distance)
		if save:
			Printing.drawImage(image, contours, targets, center)
			Printing.save(image)
		try:
			NetworkTabling.publishToTables(isVisible=isVisible, angleToGoal=angleToGoal, distance=distance, frameNum=frameNum)
		except Exception as error:
			if debug:
				print error
				print "The networktables are mean to us"
		frameNum += 1

if __name__ == '__main__':
	main()
